# Generated by Django 2.2 on 2021-03-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotable_quotes_app', '0002_auto_20210320_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='users_who_like',
        ),
        migrations.AddField(
            model_name='quote',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorited_quotes', to='quotable_quotes_app.User'),
        ),
    ]
