# Generated by Django 2.2 on 2021-03-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotable_quotes_app', '0003_auto_20210320_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='favorited_by',
        ),
    ]
