# Generated by Django 2.2 on 2021-03-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotable_quotes_app', '0004_remove_quote_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_quotes', to='quotable_quotes_app.User'),
        ),
    ]
